server:
  port: 8081

spring:
  application:
    name: auth-service
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      settings.trace: false
      path: /h2-console
