version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    networks:
      - backend

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    networks:
      - backend

  product-manager:
    build: ./product-manager
    ports:
      - "4200:4200"
    networks:
      - backend

networks:
  backend:
